### PR TITLE
[WIP] Iterators

### LINKED ISSUE #8: Remove Deref/DerefMut
Instead, have a custom iterator with an ability to spawn pointers on the way.
cc @vitvakatu

### PR DESCRIPTION
**Pull request by vitvakatu**
This is the attempt to replace `access_index`, `Deref`, `DerefMut` and `pin` with simple and powerful iterators.
@kvark I faced some troubles, I wish you can take a look and give me some advice.
According to #8:

- [x] Remove `Deref` and `DerefMut`
- [x] Remove `pin`
- [x] Implement `iter` for storage
- [ ] Implement `iter_mut` for storage
- [ ] Implement `IntoIterator` for Locks
- [x] Implement `Pointer` construction from iterator
- [ ] Implement `Deref` to `T` for iterator

Once done, it will close #8

### CODE REVIEW

**Comment by torkleyy** [comment]
Great, you could add a "Fixes #8" so it gets closed automatically. Will review later.

**Comment by vitvakatu** [comment]
@torkleyy unfortunately, it's far from being usable. Tell me your ideas if you have some

**Comment by torkleyy** [comment]
@vitvakatu Could you give a short explanation of the difficulties, please?

**Comment by vitvakatu** [comment]
My message from gitter
> One big problem is, we can't store `T` in proxy `IterItem`, because we can't move it there. `T` isn't `Clone`able, we can't move it out of borrowed context, we can't use references as it leads to massive bunch of problems with lifetimes.
And we can't get a reference to it from storage during `deref`, because we need locks.
We can't store Locks in proxy for the same reason - no opportunity to clone it, no opportunity to get a reference to it (leads to associated type's lifetime, I checked, it's not possible in current Rust)

cc @torkleyy

**Comment by torkleyy** [comment]
@vitvakatu 

Oh, is there a Gitter channel for froggy? I can't find one. Or was it written on specs' channel?

**Comment by vitvakatu** [comment]
No, there isn't atm

**Comment by DaseinPhaos** [comment]
So this new iterator type was supposed to be generated directly from `Storage`?
I thought we'd be getting it from `WriteLock`s because that would be easier to implement. 
In fact it's the only legit way that I can thought of in Safe Rust.. Maybe then the using scenario is too limited?

**Comment by kvark** [comment]
@DaseinPhaos yes, the iterators should be produced by the locks, not storages directly
The code in PR is rough and was uploaded to spark the discussion, don't take it as a final word.

**Comment by kvark** [comment]
See #12 for my attempt to do this.

**Pull request closed without merging**
